develop:
  hostname: test.spooner.zone
  user: root
  port: 22
  deploy_path: /var/www/spooner.zone/test/
  identity_file: ~/.ssh/id_rsa
  forward_agent: true
  multiplexing: false
  http_user: www-data
